### ISSUE TITLE
Timezone lookup for: GeoIP ... ERROR: Timeout

### ISSUE THREAD

**Issue by shellus** [ropg/M5ez#18]
Querying pool.ntp.org ... ERROR: No network
Querying pool.ntp.org ... ERROR: No network
Querying pool.ntp.org ... ERROR: Timeout
Querying pool.ntp.org ... ERROR: Timeout
Querying pool.ntp.org ... ERROR: Timeout
Querying pool.ntp.org ... ERROR: Timeout
Querying pool.ntp.org ... success (round trip 503 ms)
00:26:49.889 -> Received time: Saturday, 24-Nov-18 16:26:49.261 UTC
00:26:49.889 -> Timezone lookup for: Asia/Chongqing ... ERROR: Timeout

# ping timezoned.rop.nl
PING timezoned.rop.nl (82.94.252.243) 56(84) bytes of data.
64 bytes from rop.nl (82.94.252.243): icmp_seq=1 ttl=49 time=204 ms
64 bytes from rop.nl (82.94.252.243): icmp_seq=2 ttl=49 time=195 ms
64 bytes from rop.nl (82.94.252.243): icmp_seq=3 ttl=49 time=198 ms
64 bytes from rop.nl (82.94.252.243): icmp_seq=4 ttl=49 time=225 ms
64 bytes from rop.nl (82.94.252.243): icmp_seq=5 ttl=49 time=228 ms
^C
--- timezoned.rop.nl ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4002ms
rtt min/avg/max/mdev = 195.946/210.504/228.083/13.658 ms

**Comment by ropg** [comment]
Whoops, had a server problem Should be solved now. Will make things more robust soon...

**Comment by shellus** [comment]
Is there a way to set the time zone in m5ez, for example to set the time offset directly.
@ropg

**Comment by ropg** [comment]
> Is there a way to set the time zone in m5ez, for example to set the time offset directly.

Presently you can set timezone names (like "Asia/Beijing"), for which it then does a lookup. It's in the clock settings.


Rop

**Comment by shellus** [comment]
I have set it to "Asia/Chongqing", but the log still shows `Timezone lookup for: Asia/Chongqing ... ERROR: Timeout`

**Comment by ropg** [comment]
You can test my server by running (on a Mac or unix machine) `nc -u timezoned.rop.nl 2342`. Then just enter a query and end with Ctrl-D.

**Comment by shellus** [comment]
```bash
root@pi:~# echo "Asia/Macau" |  nc -u timezoned.rop.nl 2342
ERROR Timezone Not Found
^C
root@pi:~#
root@pi:~# nc -u timezoned.rop.nl 2342
Asia/Macau
ERROR Timezone Not Found
ERROR Timezone Not Found^C
root@pi:~#

```

**Comment by ropg** [comment]
It doesn't work with echo because it puts a carriage return after it:

```
$ nc -u timezoned.rop.nl 2342
Asia/MacauOK Asia/Macau CST-8
```

(Just type the "Asia/Macau" bit and then hit Ctrl-D.)

**Comment by shellus** [comment]
是的，我证实了这一点
```
Hwn I try that, i get ERROR Timezone Not Found. Which makes sense when I look at the database. Below are the possible cities for Asia, Chongqing is not on the list.

Strangely I don't even see Beijing on there, but this is the database all unix machines I have access to use, so it has to make most people happy. Not sure what's up, but Macau seems to use CST (+8) too.

If you get timeouts, something else is up, not sure what. My server works...
```
